logging:
  config: classpath:logback.xml
  path: ./logs/oauth
  level:
    org.springframework.web: DEBUG
    
server:
  port: 80
  context-path: /oauth-server
spring:
  application:
    name: oauth
  redis:
    database: 1
    host: localhost
    port: 6379
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
  security:
    oauth:
      token.uri: http://127.0.0.1:${server.port}/oauth/token
      resource:
        id: client_id
        client: 
          id: client_password
          secret: secret
  freemarker:
    allow-request-override: false  # 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
    request-context-attribute: request
    allow-session-override: false  # 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
    cache: false  # 是否启用模板缓存。
    charset: UTF-8  # 模板编码。
    check-template-location: true  # 是否检查模板位置是否存在。
    content-type: text/html  # Content-Type value.
    enabled: true  # 是否启用freemarker
    expose-request-attributes: false  # 设定所有request的属性在merge到模板的时候，是否要都添加到model中.
    expose-session-attributes: false  # 是否在merge模板的时候，将HttpSession属性都添加到model中
    expose-spring-macro-helpers: true  # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    prefer-file-system-access: true  # 是否优先从文件系统加载template，以支持热加载，默认为true
    suffix: .ftl  # 设定模板的后缀.
    template-loader-path: classpath:/templates/,classpath:/static/   # 设定模板的加载路径，多个以逗号分隔，默认: 
    settings:   # 设定FreeMarker keys.
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
  thymeleaf:
    cache: false
    model: HTML5
    prefix: classpath:/templates/
    suffix: .ftl
       


